:white_check_mark: 이미지 빌드 시에 프로젝트 version git tag로 설정

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -14,9 +14,17 @@ jobs:
     steps:
       - name: Checkout source
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          fetch-tags: true
 
       - name: Run spotlessCheck
         run: ./gradlew spotlessCheck
+
+      - name: Print build version
+        run: |
+          ./gradlew bootBuildInfo -x test --no-daemon
+          cat build/resources/main/META-INF/build-info.properties || echo "build-info not found"
 
       - name: Docker meta
         id: meta
